version: 0.2
phases:
   install:
      commands:
        - echo "Installing nginx"
        - sudo apt-get install nginx -y
   build:
     commands:
        - echo "build start"
        - cp index.html /var/www/html/
      
   post_build:
     commands:
        - echo "build done"

artifacts:
    files:
     - /var/www/html/index.html
