# Use the official Nginx image (alpine is a small version)
FROM nginx:alpine

# Copy all files from the current directory (just index.html in our case)
# into Nginx's default web server folder
COPY . /usr/share/nginx/html
